"""The launcher A/B is only interpretable if the arms differ in one place.

Anything else that drifts between the two files becomes a second, unrecorded
treatment. See PREREGISTRATION.md.
"""

import json
import subprocess
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTROL = ROOT / "prompts" / "TRY-LEANFRONTIER.md"
EXTENSION = ROOT / "prompts" / "TRY-LEANFRONTIER-EXTEND.md"

# The paragraph the experiment varies, plus the title line that names the arm.
CONTROL_BLOCK = """Start from current `main` in a fork or branch. Inspect the existing library and
catalogue before choosing a subject: prefer an uncovered area or a genuine
extension over a near duplicate."""

EXTENSION_BLOCK = """Start from current `main` in a fork or branch. Read the catalogue and choose an
accepted submission to build on. Import its module and prove something that
depends on it: a generalization, a consequence, or a result that needs it as a
lemma. A near duplicate is still a near duplicate and will be rejected."""


class LauncherArms(unittest.TestCase):
    def setUp(self) -> None:
        self.control = CONTROL.read_text()
        self.extension = EXTENSION.read_text()

    def test_each_arm_carries_its_own_block(self) -> None:
        self.assertIn(CONTROL_BLOCK, self.control)
        self.assertIn(EXTENSION_BLOCK, self.extension)
        self.assertNotIn(EXTENSION_BLOCK, self.control)
        self.assertNotIn(CONTROL_BLOCK, self.extension)

    def test_arms_are_otherwise_identical(self) -> None:
        """Normalise away the varied block and the title, then compare words.

        Comparison is word-level, not byte-level: the two blocks are different
        lengths, so the sentence following them rewraps. Line breaks are not a
        treatment. Any difference in the words themselves is.
        """
        control = self.control.replace(CONTROL_BLOCK, "<BLOCK>").replace(
            "# Try LeanFrontier with an agent", "<TITLE>", 1)
        extension = self.extension.replace(EXTENSION_BLOCK, "<BLOCK>").replace(
            "# Try LeanFrontier with an agent (extension arm)", "<TITLE>", 1)
        self.assertEqual(control.split(), extension.split())

    def test_preregistration_names_both_arms(self) -> None:
        prereg = (ROOT / "PREREGISTRATION.md").read_text()
        self.assertIn("TRY-LEANFRONTIER.md", prereg)
        self.assertIn("TRY-LEANFRONTIER-EXTEND.md", prereg)

    def test_amendments_are_added_not_substituted(self) -> None:
        """A pre-registration rewritten in place records nothing. The original
        design must stay legible next to what replaced it."""
        prereg = (ROOT / "PREREGISTRATION.md").read_text()
        self.assertIn("## Amendment", prereg)
        # The stopping point and the null-result commitment survive every
        # amendment; they are the parts an amendment could quietly soften.
        self.assertIn("18 accepted submissions per arm", prereg)
        self.assertIn("no effect larger than ~4x", prereg)

    def test_assignment_ledger_is_generated_output(self) -> None:
        text = (ROOT / "experiments" / "launcher-ab.csv").read_text()
        self.assertIn("GENERATED by tools/generate_experiment_ledger.py", text)
        rows = [l for l in text.splitlines() if l and not l.startswith("#")]
        self.assertEqual(rows[0], "submission_id,arm,producer_model")
        for row in rows[1:]:
            self.assertIn(row.split(",")[1], {"A", "B", "unassigned"})

    def test_the_arm_travels_inside_the_submission_claim(self) -> None:
        """A side ledger cannot be written by a submission: CONTRACT.md section 2
        permits only Lean source and one Submissions/*.json, so appending to
        experiments/ would be a PATH_POLICY_VIOLATION."""
        schema = json.loads((ROOT / "schema" / "submission.schema.json").read_text())
        self.assertEqual(schema["properties"]["launcher_arm"]["enum"], ["A", "B", None])
        self.assertNotIn("launcher_arm", schema["required"])


class ExperimentLedger(unittest.TestCase):
    def test_the_committed_ledger_is_at_a_fixed_point(self) -> None:
        generated = subprocess.run(
            [sys.executable, str(ROOT / "tools" / "generate_experiment_ledger.py"),
             "--root", str(ROOT), "--check"],
            capture_output=True, text=True)
        self.assertEqual(generated.returncode, 0, generated.stdout + generated.stderr)


if __name__ == "__main__":
    unittest.main()
