import LeanFrontier.Topology.FurstenbergQuotients
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.FiniteIndexNormalSubgroup
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.Ideal.Operations

/-!
# Finite-index subgroups of the integers as cyclic quotients

The Furstenberg topology is already identified in LeanFrontier with the topology generated by the
reduction maps `ℤ → ZMod n`. Mathlib's profinite completion, on the other hand, is indexed by
all finite-index normal additive subgroups.

This module supplies the missing bridge for `ℤ`: every object of that generic indexing category
is canonically the subgroup of multiples of its index, and its quotient is therefore the
corresponding `ZMod`.

This is intended as the first cofinality step toward identifying the Furstenberg topology with
the topology induced by the canonical map into the additive profinite completion.
-/

namespace LeanFrontier.Int

open QuotientAddGroup

/-- Every finite-index normal additive subgroup of `ℤ` is the subgroup of multiples of its
index. The index is therefore the canonical nonnegative modulus attached to the subgroup. -/
theorem finiteIndexNormalAddSubgroup_eq_zmultiples_index
    (H : FiniteIndexNormalAddSubgroup ℤ) :
    H.toAddSubgroup =
      AddSubgroup.zmultiples (H.toAddSubgroup.index : ℤ) := by
  obtain ⟨a, ha⟩ :=
    Submodule.IsPrincipal.principal H.toAddSubgroup.toIntSubmodule
  have hgen : H.toAddSubgroup = AddSubgroup.zmultiples a := by
    have ha' := congrArg Submodule.toAddSubgroup ha
    rw [Submodule.span_singleton_toAddSubgroup_eq_zmultiples,
      AddSubgroup.toIntSubmodule_toAddSubgroup] at ha'
    exact ha'
  rw [hgen, Int.index_zmultiples]
  exact (Int.zmultiples_natAbs a).symm

/-- The generic finite quotient of `ℤ` indexed by `H` is canonically the cyclic quotient
`ZMod H.index`. -/
noncomputable def finiteIndexQuotientEquivZMod
    (H : FiniteIndexNormalAddSubgroup ℤ) :
    (ℤ ⧸ H.toAddSubgroup) ≃+ ZMod H.toAddSubgroup.index :=
  (quotientAddEquivOfEq (finiteIndexNormalAddSubgroup_eq_zmultiples_index H)).trans
    (Int.quotientZMultiplesNatEquivZMod H.toAddSubgroup.index)

/-- Under the canonical cyclic-quotient equivalence, the generic quotient class of an integer is
exactly its reduction modulo the subgroup index. -/
@[simp]
theorem finiteIndexQuotientEquivZMod_mk
    (H : FiniteIndexNormalAddSubgroup ℤ) (x : ℤ) :
    finiteIndexQuotientEquivZMod H (QuotientAddGroup.mk x) =
      zmodReduction H.toAddSubgroup.index x := by
  rfl

end LeanFrontier.Int
