import Mathlib.Data.Set.Finite.Basic
import Mathlib.RingTheory.Int.Basic
import Mathlib.Topology.Bases

/-!
# The Furstenberg topology on the integers

Furstenberg's 1955 proof of the infinitude of primes topologizes `ℤ` with the *evenly spaced
topology*, generated by the two-sided arithmetic progressions `{x | b ∣ x - a}` with `b ≠ 0`.
Three structural facts drive the argument: the progressions form a topological basis, each
progression is clopen, and every nonempty open set is infinite. Since every integer other
than `±1` has a prime divisor, the progressions `pℤ` over all primes cover `ℤ \ {1, -1}`;
were there finitely many primes, that union would be closed, making `{1, -1}` a finite
nonempty open set.

This module builds the topology and proves those facts, ending with the covering identity
and the finiteness engine `infinite_of_iUnion_eq_compl`: any set of nonzero naturals whose
progressions cover `ℤ \ {1, -1}` is infinite. Composing the last two statements is exactly
Furstenberg's proof; the composed statement itself, the infinitude of primes, is already in
Mathlib as `Nat.infinite_setOf_prime` and is therefore deliberately not restated here.

## Main definitions

* `LeanFrontier.Int.arithProgression` - the two-sided arithmetic progression
  `{x | b ∣ x - a}`.
* `LeanFrontier.Int.furstenbergTopology` - the topology on `ℤ` generated by the progressions
  with nonzero step.

## Main statements

* `LeanFrontier.Int.isTopologicalBasis_arithProgression` - the progressions form a basis.
* `LeanFrontier.Int.isOpen_arithProgression`, `LeanFrontier.Int.isClosed_arithProgression` -
  each progression with nonzero step is clopen.
* `LeanFrontier.Int.infinite_arithProgression`,
  `LeanFrontier.Int.infinite_of_isOpen` - progressions are infinite, hence so is every
  nonempty open set.
* `LeanFrontier.Int.iUnion_prime_arithProgression` - the progressions `pℤ` over all primes
  cover exactly `ℤ \ {1, -1}`.
* `LeanFrontier.Int.infinite_of_iUnion_eq_compl` - any set of nonzero naturals achieving
  that covering is infinite.

## Implementation notes

The topology is a plain definition, not an instance: `ℤ` keeps its order topology elsewhere,
and every statement here names `furstenbergTopology` explicitly through the scoped notation
`IsOpen[t]` / `IsClosed[t]`.

A progression is `{x | b ∣ x - a}` rather than an existential image, so membership proofs
are divisibility facts. Closedness reduces to a positive step via `abs_dvd`, and the
complement of a step-`b` progression is then the union of the `b - 1` progressions shifted
by the nonzero residues, exhibited with `Int.ediv_add_emod`. Basis intersections need no gcd:
inside `arithProgression a₁ b₁ ∩ arithProgression a₂ b₂` the point `x` lies in
`arithProgression x (b₁ * b₂)`, which is contained in both.
-/

namespace LeanFrontier.Int

open Set Topology TopologicalSpace

/-- The two-sided arithmetic progression through `a` with step `b`: the set
`{..., a - b, a, a + b, a + 2 * b, ...}` of integers congruent to `a` modulo `b`. -/
def arithProgression (a b : ℤ) : Set ℤ := {x : ℤ | b ∣ x - a}

theorem mem_arithProgression {x a b : ℤ} : x ∈ arithProgression a b ↔ b ∣ x - a := Iff.rfl

theorem self_mem_arithProgression (a b : ℤ) : a ∈ arithProgression a b := by
  simp [mem_arithProgression]

/-- The Furstenberg (evenly spaced) topology on `ℤ`: the topology generated by the
arithmetic progressions with nonzero step. Not registered as an instance. -/
@[instance_reducible] def furstenbergTopology : TopologicalSpace ℤ :=
  generateFrom {S : Set ℤ | ∃ a b, b ≠ 0 ∧ S = arithProgression a b}

/-- The arithmetic progressions with nonzero step are a basis of the Furstenberg
topology. -/
theorem isTopologicalBasis_arithProgression :
    @IsTopologicalBasis ℤ furstenbergTopology
      {S : Set ℤ | ∃ a b, b ≠ 0 ∧ S = arithProgression a b} := by
  letI := furstenbergTopology
  refine ⟨?_, ?_, rfl⟩
  · rintro t₁ ⟨a₁, b₁, hb₁, rfl⟩ t₂ ⟨a₂, b₂, hb₂, rfl⟩ x ⟨hx₁, hx₂⟩
    refine ⟨arithProgression x (b₁ * b₂), ⟨x, b₁ * b₂, mul_ne_zero hb₁ hb₂, rfl⟩,
      self_mem_arithProgression x _, fun y hy => ⟨?_, ?_⟩⟩
    · have h1 : b₁ ∣ y - x := (dvd_mul_right b₁ b₂).trans hy
      have h2 := dvd_add h1 hx₁
      rwa [sub_add_sub_cancel] at h2
    · have h1 : b₂ ∣ y - x := (dvd_mul_left b₂ b₁).trans hy
      have h2 := dvd_add h1 hx₂
      rwa [sub_add_sub_cancel] at h2
  · rw [sUnion_eq_univ_iff]
    exact fun x => ⟨arithProgression x 1, ⟨x, 1, one_ne_zero, rfl⟩,
      self_mem_arithProgression x 1⟩

/-- Arithmetic progressions with nonzero step are open. -/
theorem isOpen_arithProgression (a b : ℤ) (hb : b ≠ 0) :
    IsOpen[furstenbergTopology] (arithProgression a b) := by
  letI := furstenbergTopology
  exact isTopologicalBasis_arithProgression.isOpen ⟨a, b, hb, rfl⟩

/-- Arithmetic progressions with nonzero step are closed: after reducing to a positive
step via `abs_dvd`, the complement is the union of the progressions shifted by the nonzero
residues. Together with `isOpen_arithProgression`, the basic sets of the Furstenberg
topology are clopen. -/
theorem isClosed_arithProgression (a : ℤ) {b : ℤ} (hb : b ≠ 0) :
    IsClosed[furstenbergTopology] (arithProgression a b) := by
  letI := furstenbergTopology
  have habs : arithProgression a b = arithProgression a |b| :=
    Set.ext fun x => (abs_dvd b (x - a)).symm
  have hpos : 0 < |b| := abs_pos.mpr hb
  rw [habs]
  generalize hgen : |b| = c at hpos ⊢
  have hcompl : (arithProgression a c)ᶜ
      = ⋃ r ∈ Set.Ioo (0 : ℤ) c, arithProgression (a + r) c := by
    ext x
    simp only [mem_compl_iff, mem_arithProgression, mem_iUnion, mem_Ioo, exists_prop]
    constructor
    · intro hnd
      refine ⟨(x - a) % c, ⟨?_, Int.emod_lt_of_pos _ hpos⟩, ?_⟩
      · rcases (Int.emod_nonneg (x - a) hpos.ne').lt_or_eq with h | h
        · exact h
        · exact absurd (Int.dvd_of_emod_eq_zero h.symm) hnd
      · have hdm := Int.emod_add_ediv_mul (x - a) c
        refine ⟨(x - a) / c, ?_⟩
        have hcomm : (x - a) / c * c = c * ((x - a) / c) := mul_comm _ _
        linarith
    · rintro ⟨r, ⟨hr0, hrc⟩, hdvd'⟩ hdvd
      have hr : c ∣ r := by
        have h := dvd_sub hdvd hdvd'
        have heq : (x - a) - (x - (a + r)) = r := by ring
        rwa [heq] at h
      have := Int.le_of_dvd hr0 hr
      linarith
  rw [← isOpen_compl_iff, hcompl]
  exact isOpen_biUnion fun r _ => isOpen_arithProgression _ _ hpos.ne'

/-- An arithmetic progression with nonzero step is infinite. -/
theorem infinite_arithProgression (a : ℤ) {b : ℤ} (hb : b ≠ 0) :
    (arithProgression a b).Infinite :=
  Set.infinite_of_injective_forall_mem (f := fun k : ℤ => a + b * k)
    (fun k₁ k₂ h => mul_left_cancel₀ hb (add_left_cancel h))
    (fun k => by
      show b ∣ (a + b * k) - a
      have h : (a + b * k) - a = b * k := by ring
      rw [h]
      exact dvd_mul_right b k)

/-- Every nonempty open set of the Furstenberg topology is infinite: it contains a whole
arithmetic progression around each of its points. -/
theorem infinite_of_isOpen {U : Set ℤ} (hU : IsOpen[furstenbergTopology] U)
    (hne : U.Nonempty) : U.Infinite := by
  letI := furstenbergTopology
  obtain ⟨x, hx⟩ := hne
  obtain ⟨V, ⟨a, b, hb, rfl⟩, -, hVU⟩ :=
    isTopologicalBasis_arithProgression.exists_subset_of_mem_open hx hU
  exact (infinite_arithProgression a hb).mono hVU

/-- Furstenberg's covering identity: the progressions `pℤ` over all primes cover exactly
the integers other than `1` and `-1`. -/
theorem iUnion_prime_arithProgression :
    ⋃ p ∈ {p : ℕ | p.Prime}, arithProgression 0 (p : ℤ) = ({1, -1} : Set ℤ)ᶜ := by
  ext x
  simp only [mem_iUnion, mem_setOf_eq, mem_arithProgression, sub_zero, mem_compl_iff,
    mem_insert_iff, mem_singleton_iff, exists_prop]
  constructor
  · rintro ⟨p, hp, hdvd⟩ h
    have hone : (p : ℤ) ∣ 1 := by
      rcases h with rfl | rfl
      · exact hdvd
      · exact (dvd_neg).mp hdvd
    have : p ∣ 1 := by exact_mod_cast hone
    exact hp.ne_one (Nat.dvd_one.mp this)
  · intro hx
    have hx1 : x ≠ 1 := fun h => hx (Or.inl h)
    have hx2 : x ≠ -1 := fun h => hx (Or.inr h)
    have hna : x.natAbs ≠ 1 := by
      intro h1
      rcases Int.natAbs_eq_iff.mp h1 with h | h
      · exact hx1 (by exact_mod_cast h)
      · exact hx2 (by exact_mod_cast h)
    obtain ⟨p, hp, hdvd⟩ := Int.exists_prime_and_dvd hna
    exact ⟨p.natAbs, Int.prime_iff_natAbs_prime.mp hp, by rwa [Int.natAbs_dvd]⟩

/-- The engine of Furstenberg's proof: a set of nonzero naturals whose progressions cover
all of `ℤ \ {1, -1}` cannot be finite, since a finite union of closed progressions is
closed, and `{1, -1}` cannot be open, being finite and nonempty. Applied to the set of
primes via `iUnion_prime_arithProgression`, this yields the infinitude of primes, which
Mathlib already states as `Nat.infinite_setOf_prime`. -/
theorem infinite_of_iUnion_eq_compl {S : Set ℕ} (h0 : 0 ∉ S)
    (hcov : ⋃ p ∈ S, arithProgression 0 (p : ℤ) = ({1, -1} : Set ℤ)ᶜ) : S.Infinite := by
  by_contra hinf
  rw [Set.not_infinite] at hinf
  have hfin : S.Finite := hinf
  letI := furstenbergTopology
  have hclosed : IsClosed (⋃ p ∈ S, arithProgression 0 (p : ℤ)) :=
    hfin.isClosed_biUnion fun p hp =>
      isClosed_arithProgression 0 (Int.natCast_ne_zero.mpr (fun h => h0 (h ▸ hp)))
  rw [hcov] at hclosed
  have hopen : IsOpen ({1, -1} : Set ℤ) := isClosed_compl_iff.mp hclosed
  exact infinite_of_isOpen hopen ⟨1, by simp⟩
    ((Set.finite_singleton (-1)).insert 1)

end LeanFrontier.Int
