import LeanFrontier.Topology.FurstenbergFiniteIndex
import Mathlib.Topology.Order

/-!
# Furstenberg topology from all finite-index quotients of the integers

LeanFrontier already identifies the Furstenberg topology with the topology generated by the
cyclic reductions `ℤ → ZMod n`, and it classifies every finite-index normal additive subgroup
of `ℤ` as a subgroup of multiples. Mathlib's profinite completion is instead indexed by *all*
finite-index normal additive subgroups.

This module closes that representation gap. We define the topology induced jointly by all generic
quotient maps

`ℤ → ℤ ⧸ H`

with each finite quotient discrete, and prove that it is exactly the already accepted cyclic
finite-quotient topology. Consequently it is exactly the Furstenberg topology.

This is the cofinality/topology comparison needed before identifying the Furstenberg topology
with the topology induced by Mathlib's canonical map into the additive profinite completion.
-/

namespace LeanFrontier.Int

open Topology TopologicalSpace

/-- The topology on `ℤ` induced jointly by all quotient maps by finite-index normal additive
subgroups, with every finite quotient given the discrete topology. -/
@[instance_reducible] def genericFiniteQuotientTopology : TopologicalSpace ℤ :=
  ⨅ H : FiniteIndexNormalAddSubgroup ℤ,
    (⊥ : TopologicalSpace (ℤ ⧸ H.toAddSubgroup)).induced
      (fun x : ℤ => (QuotientAddGroup.mk x : ℤ ⧸ H.toAddSubgroup))

private theorem continuous_genericQuotientMk
    (H : FiniteIndexNormalAddSubgroup ℤ) :
    Continuous[
      furstenbergTopology,
      (⊥ : TopologicalSpace (ℤ ⧸ H.toAddSubgroup))]
      (fun x : ℤ => (QuotientAddGroup.mk x : ℤ ⧸ H.toAddSubgroup)) := by
  let n := H.toAddSubgroup.index
  have hn : n ≠ 0 := AddSubgroup.FiniteIndex.index_ne_zero
  let e := finiteIndexQuotientEquivZMod H
  letI : TopologicalSpace ℤ := furstenbergTopology
  letI : TopologicalSpace (ZMod n) := ⊥
  let _ : DiscreteTopology (ZMod n) := ⟨rfl⟩
  letI : TopologicalSpace (ℤ ⧸ H.toAddSubgroup) := ⊥
  let _ : DiscreteTopology (ℤ ⧸ H.toAddSubgroup) := ⟨rfl⟩
  have hz : Continuous (zmodReduction n) := by
    simpa [n] using continuous_zmodReduction hn
  have he : Continuous e.symm := continuous_of_discreteTopology
  have hcomp := he.comp hz
  change Continuous (fun x : ℤ =>
    (QuotientAddGroup.mk x : ℤ ⧸ H.toAddSubgroup))
  convert hcomp using 1
  funext x
  apply e.injective
  simp [e, n]

private def zmultiplesFiniteIndexNormal
    (n : ℕ) (hn : n ≠ 0) : FiniteIndexNormalAddSubgroup ℤ := by
  let A : AddSubgroup ℤ := AddSubgroup.zmultiples (n : ℤ)
  let _ : NeZero n := ⟨hn⟩
  letI : Finite (ℤ ⧸ A) :=
    Finite.of_equiv (ZMod n)
      (Int.quotientZMultiplesNatEquivZMod n).symm.toEquiv
  letI : A.FiniteIndex := AddSubgroup.finiteIndex_of_finite_quotient
  exact FiniteIndexNormalAddSubgroup.ofAddSubgroup A

private theorem zmultiplesFiniteIndexNormal_toAddSubgroup
    (n : ℕ) (hn : n ≠ 0) :
    (zmultiplesFiniteIndexNormal n hn).toAddSubgroup =
      AddSubgroup.zmultiples (n : ℤ) := by
  simp [zmultiplesFiniteIndexNormal]

/-- The topology generated by all finite-index quotients of `ℤ` is exactly the topology
generated by the nonzero cyclic quotients `ZMod n`.

This is the cofinality statement at the level of topologies: the generic finite-quotient diagram
used by profinite completion contributes no additional open sets beyond ordinary congruence
modulo nonzero natural numbers. -/
theorem genericFiniteQuotientTopology_eq_finiteQuotientTopology :
    genericFiniteQuotientTopology = finiteQuotientTopology := by
  apply le_antisymm
  · rw [finiteQuotientTopology]
    refine le_iInf fun n => ?_
    let H := zmultiplesFiniteIndexNormal n.1 n.2
    have hle :
        genericFiniteQuotientTopology ≤
          (⊥ : TopologicalSpace (ℤ ⧸ H.toAddSubgroup)).induced
            (fun x : ℤ => (QuotientAddGroup.mk x : ℤ ⧸ H.toAddSubgroup)) := by
      rw [genericFiniteQuotientTopology]
      exact iInf_le _ H
    have hH :
        H.toAddSubgroup = AddSubgroup.zmultiples (n.1 : ℤ) :=
      zmultiplesFiniteIndexNormal_toAddSubgroup n.1 n.2
    rw [hH] at hle
    letI : TopologicalSpace ℤ := genericFiniteQuotientTopology
    letI : TopologicalSpace
        (ℤ ⧸ AddSubgroup.zmultiples (n.1 : ℤ)) := ⊥
    let _ : DiscreteTopology
        (ℤ ⧸ AddSubgroup.zmultiples (n.1 : ℤ)) := ⟨rfl⟩
    letI : TopologicalSpace (ZMod n.1) := ⊥
    let _ : DiscreteTopology (ZMod n.1) := ⟨rfl⟩
    have hmk :
        Continuous (fun x : ℤ =>
          (QuotientAddGroup.mk x :
            ℤ ⧸ AddSubgroup.zmultiples (n.1 : ℤ))) :=
      continuous_iff_le_induced.mpr hle
    have he :
        Continuous (Int.quotientZMultiplesNatEquivZMod n.1 :
          (ℤ ⧸ AddSubgroup.zmultiples (n.1 : ℤ)) → ZMod n.1) :=
      continuous_of_discreteTopology
    have hcomp := he.comp hmk
    apply Continuous.le_induced
    simpa only [Function.comp_apply, zmodReduction] using hcomp
  · rw [genericFiniteQuotientTopology,
      ← furstenbergTopology_eq_finiteQuotientTopology]
    refine le_iInf fun H => ?_
    exact Continuous.le_induced (continuous_genericQuotientMk H)

/-- The Furstenberg topology is exactly the topology induced jointly by all generic finite-index
quotient maps of the additive group of integers. -/
theorem furstenbergTopology_eq_genericFiniteQuotientTopology :
    furstenbergTopology = genericFiniteQuotientTopology := by
  rw [furstenbergTopology_eq_finiteQuotientTopology,
    genericFiniteQuotientTopology_eq_finiteQuotientTopology]

end LeanFrontier.Int
