import LeanFrontier.Topology.Furstenberg
import Mathlib.Topology.Algebra.Group.GroupTopology

/-!
# Algebraic structure of the Furstenberg topology

The Furstenberg topology on `ℤ` is generated by congruence classes.  This module records the
corresponding additive-group structure without changing the ordinary global topology instance on
`ℤ`.

The key observations are elementary:

* negation sends the progression through `a` modulo `b` to the progression through `-a`
  modulo `b`;
* the preimage under addition of a progression through `a` modulo `b` is the union, over
  `c : ℤ`, of
  `arithProgression c b × arithProgression (a - c) b`.

These identities make negation and addition continuous for the named Furstenberg topology.  The
two continuity proofs are then bundled into `furstenbergAddGroupTopology`, a local
`AddGroupTopology ℤ` whose underlying topology is exactly `furstenbergTopology`.
-/

namespace LeanFrontier.Int

open Set Topology TopologicalSpace

private theorem preimage_neg_arithProgression (a b : ℤ) :
    (fun x : ℤ => -x) ⁻¹' arithProgression a b = arithProgression (-a) b := by
  ext x
  simp only [mem_preimage, mem_arithProgression]
  constructor
  · intro h
    have h' : b ∣ -((-x) - a) := dvd_neg.mpr h
    convert h' using 1 <;> ring
  · intro h
    have h' : b ∣ -(x - (-a)) := dvd_neg.mpr h
    convert h' using 1 <;> ring

private theorem preimage_add_arithProgression (a b : ℤ) :
    (fun p : ℤ × ℤ => p.1 + p.2) ⁻¹' arithProgression a b =
      ⋃ c : ℤ, arithProgression c b ×ˢ arithProgression (a - c) b := by
  ext p
  simp only [mem_preimage, mem_iUnion, mem_prod, mem_arithProgression]
  constructor
  · intro h
    refine ⟨p.1, ?_, ?_⟩
    · simp
    · convert h using 1 <;> ring
  · rintro ⟨c, hx, hy⟩
    have h := dvd_add hx hy
    convert h using 1 <;> ring

private theorem isOpen_preimage_add_arithProgression (a b : ℤ) (hb : b ≠ 0) :
    IsOpen[@instTopologicalSpaceProd ℤ ℤ furstenbergTopology furstenbergTopology]
      ((fun p : ℤ × ℤ => p.1 + p.2) ⁻¹' arithProgression a b) := by
  letI := furstenbergTopology
  rw [preimage_add_arithProgression]
  exact isOpen_iUnion fun c =>
    (isOpen_arithProgression c b hb).prod
      (isOpen_arithProgression (a - c) b hb)

/-- Negation is continuous for the named Furstenberg topology on `ℤ`.

The topology is installed only locally by the theorem statement; this does not alter the ordinary
global topology instance on the integers. -/
theorem continuous_neg_furstenberg :
    Continuous[furstenbergTopology, furstenbergTopology] (fun x : ℤ => -x) := by
  letI := furstenbergTopology
  rw [isTopologicalBasis_arithProgression.continuous_iff]
  rintro _ ⟨a, b, hb, rfl⟩
  rw [preimage_neg_arithProgression]
  exact isOpen_arithProgression (-a) b hb

/-- Addition is continuous for the named Furstenberg topology on `ℤ`.

Again, the Furstenberg topology is local to the statement; the product topology on `ℤ × ℤ` is
therefore the product of two copies of `furstenbergTopology`. -/
theorem continuous_add_furstenberg :
    Continuous[
      @instTopologicalSpaceProd ℤ ℤ furstenbergTopology furstenbergTopology,
      furstenbergTopology] (fun p : ℤ × ℤ => p.1 + p.2) := by
  letI := furstenbergTopology
  rw [isTopologicalBasis_arithProgression.continuous_iff]
  rintro _ ⟨a, b, hb, rfl⟩
  exact isOpen_preimage_add_arithProgression a b hb

/-- The Furstenberg topology, bundled as an additive-group topology on `ℤ`.

This is deliberately a named value rather than a global instance, so importing this module does
not replace the usual topology on the integers. -/
def furstenbergAddGroupTopology : AddGroupTopology ℤ where
  toTopologicalSpace := furstenbergTopology
  continuous_add := by
    simpa only using continuous_add_furstenberg
  continuous_neg := by
    simpa only using continuous_neg_furstenberg

end LeanFrontier.Int
