#!/usr/bin/env python3
"""Count the receiver's verdicts per week and diagnostic code.

The receiver's rejections are the protocol's most direct evidence of what
mechanical admission filters, and until now they lived only in workflow runs
that expire. This appends, for every complete week not yet recorded, how many
submission validations carried each diagnostic code: `ACCEPTED` for runs that
passed, `REPORT_EXPIRED` for runs whose report has expired, `NO_DIAGNOSTIC` for
a rejected report that names no code.

Only runs that validated a submission count: they are the ones that upload the
receiver's report. Validations of generated output and maintenance pull
requests take other paths and upload none, and neither do runs cancelled
before the receiver started; they are not verdicts on a submission.

Aggregates only. No source, no submitter, no pull-request number: a week and a
code and a count. A run that carries two codes counts once under each. Re-runs
of the same head count separately, since each is a verdict the submitter saw.

Weeks are ISO weeks named by their Monday. A week is recorded once, after it
ends, and never rewritten: the reports behind it expire, so the file is the
only lasting copy. The gate on generated output enforces append-only.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import subprocess
import time
import zipfile
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = Path("experiments") / "rejections.csv"
WORKFLOW = "validate-submission.yml"
ARTIFACT = "leanfrontier-validation-report"
HEADER = """# GENERATED by tools/collect_rejections.py -- do not edit.
# Validation runs per ISO week (named by its Monday) and diagnostic code.
# Submission validations only. ACCEPTED: passed. REPORT_EXPIRED: the report
# expired before it was counted. NO_DIAGNOSTIC: rejected without a code.
# A run with several codes counts once under each. Aggregates only: no source,
# no submitter, no pull request. Weeks are appended once, after they end.
week,code,runs
"""


def gh_bytes(*args: str) -> bytes:
    """Run gh, retrying transient failures: a backfill makes a thousand calls."""
    for attempt in range(4):
        result = subprocess.run(["gh", *args], capture_output=True)
        if result.returncode == 0:
            return result.stdout
        if attempt < 3:
            time.sleep(2 ** attempt * 5)
    raise RuntimeError(f"gh {' '.join(args)} failed: {result.stderr.decode(errors='replace').strip()}")


def gh(*args: str) -> str:
    return gh_bytes(*args).decode("utf-8")


def monday(day: date) -> date:
    return day - timedelta(days=day.weekday())


def recorded_weeks(text: str) -> set[str]:
    return {line.split(",", 1)[0] for line in text[len(HEADER):].splitlines() if line}


def run_ids(repository: str, week: date) -> list[int]:
    """Every completed run created in one closed week, each once.

    One week at a time, because the listing is newest first and paged: while
    new runs are created, pages shift and a single long listing counts some
    runs twice. The first backfill on main did (week of 17 August: 44 accepted
    instead of 37). A closed week gains no new runs, so its pages hold still.
    """
    window = f"{week.isoformat()}..{(week + timedelta(days=6)).isoformat()}"
    listing = gh("api", "--paginate",
                 f"repos/{repository}/actions/workflows/{WORKFLOW}/runs?status=completed&per_page=100&created={window}",
                 "--jq", ".workflow_runs[].id")
    return sorted({int(line) for line in listing.split()})


def codes_of(repository: str, run_id: int) -> set[str] | None:
    """The run's diagnostic codes, or None when it validated no submission.

    GitHub keeps an artifact's record after the artifact expires, so a run
    that uploaded a report and one that never did can still be told apart.
    """
    artifacts = json.loads(gh("api", f"repos/{repository}/actions/runs/{run_id}/artifacts"))
    reports = [a for a in artifacts.get("artifacts", []) if a.get("name") == ARTIFACT]
    if not reports:
        return None
    wanted = [a for a in reports if not a.get("expired")]
    if not wanted:
        return {"REPORT_EXPIRED"}
    archive = gh_bytes("api", f"repos/{repository}/actions/artifacts/{wanted[0]['id']}/zip")
    with zipfile.ZipFile(io.BytesIO(archive)) as bundle:
        names = bundle.namelist()
        # The formal report supersedes the preflight report when both exist.
        chosen = next((n for n in names if n.endswith("report-output/report.json") or n == "report.json"), None) \
            or next((n for n in names if n.endswith("preflight-report.json")), None)
        if chosen is None:
            return {"NO_DIAGNOSTIC"}
        report = json.loads(bundle.read(chosen))
    if report.get("accepted") is True:
        return {"ACCEPTED"}
    found = {d.get("code") for d in report.get("diagnostics", []) if isinstance(d, dict) and isinstance(d.get("code"), str)}
    return found or {"NO_DIAGNOSTIC"}


def new_rows(repository: str, existing: str, today: date, since: date) -> list[str]:
    done = recorded_weeks(existing)
    rows: list[str] = []
    week = monday(since)
    while week < monday(today):
        if week.isoformat() not in done:
            counts: Counter = Counter()
            for run_id in run_ids(repository, week):
                codes = codes_of(repository, run_id)
                if codes is not None:
                    counts.update(codes)
            rows.extend(f"{week.isoformat()},{code},{counts[code]}\n" for code in sorted(counts))
        week += timedelta(days=7)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", "carlok/LeanFrontier"))
    parser.add_argument("--since", type=date.fromisoformat, default=date(2026, 8, 10),
                        help="earliest run date to consider (runs before it have no reports)")
    parser.add_argument("--today", type=date.fromisoformat, default=date.today())
    args = parser.parse_args()
    destination = args.root / DESTINATION
    existing = destination.read_text(encoding="utf-8") if destination.exists() else HEADER
    rows = new_rows(args.repository, existing, args.today, args.since)
    if rows:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(existing + "".join(rows), encoding="utf-8")
    print(f"{len(rows)} rows appended")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
