#!/usr/bin/env python3
"""Derive the accumulation series registered in PREREGISTRATION.md.

The launcher A/B was suspended on 23 September 2026 with three of its
thirty-six arm-tagged submissions. What replaced it is this: an observational
series over the whole corpus, no arms, no treatment, no causal claim.

Each row is the corpus as it stood when one submission was accepted, computed
from that commit's tree rather than reconstructed from today's files, so a
later edit to a module cannot rewrite earlier history. The metrics are the ones
registered in advance: internal import edges, edges per module, the share of
modules importing at least one other, maximum in-degree, maximum depth, and
whether the submission imported a module accepted in the preceding seven days.

The add-only rule of 22 September forces an import edge for any submission that
extends an accepted module, so rows from that date onward are not comparable
with earlier ones. The `add_only_rule` column marks the boundary rather than
leaving a reader to discover it.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = Path("experiments") / "accumulation.csv"
ADD_ONLY_SINCE = date(2026, 9, 22)
RECENT_DAYS = 7
IMPORT_RE = re.compile(r"^import (LeanFrontier\S*)", re.MULTILINE)

HEADER = """# GENERATED by tools/generate_accumulation_series.py -- do not edit.
# One row per accepted submission, in order of acceptance, each computed from
# the repository tree at that commit. See the "Suspension and replacement"
# section of PREREGISTRATION.md for what this measures and what it cannot show.
#
# add_only_rule is true from 2026-09-22, when ordinary submissions became
# add-only: extending an accepted module then requires importing it, which
# creates an edge by construction. Rows on either side of that boundary are
# reported separately, and the earlier ones are the cleaner evidence.
date,submission_id,modules,edges,edges_per_module,connected_share,max_in_degree,max_depth,imports_recent,add_only_rule
"""


def run(args: list[str], root: Path) -> str:
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True, check=True).stdout


def claims_at(commit: str, root: Path) -> set[str]:
    listing = run(["ls-tree", "--name-only", commit, "--", "Submissions/"], root)
    return {Path(line).stem for line in listing.splitlines() if line.endswith(".json")}


def submission_commits(root: Path) -> list[tuple[str, str, str]]:
    """(commit, date, submission_id) for each claim, at the commit that put it on the default branch.

    Walking the default branch's first-parent history, rather than looking for
    the commit that added the file, because that commit sits on the submission's
    own branch: its tree is the branch, which can lack modules that reached the
    corpus while the pull request was open. A row must describe the corpus the
    submission actually joined.
    """
    log = run(["log", "--first-parent", "--reverse", "--format=%H\t%ad", "--date=short"], root)
    history = [line.split("\t", 1) for line in log.splitlines() if "\t" in line]
    commits: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for commit, day in history:
        current = claims_at(commit, root)
        for submission in sorted(current - seen):
            commits.append((commit, day, submission))
        seen |= current
    return commits


def modules_at(commit: str, root: Path) -> dict[str, str]:
    """Module name to source, for every corpus module present at `commit`."""
    listing = run(["ls-tree", "-r", commit, "--", "LeanFrontier"], root)
    blobs: dict[str, str] = {}
    for line in listing.splitlines():
        meta, _, path = line.partition("\t")
        if not path.endswith(".lean"):
            continue
        name = "LeanFrontier." + path[len("LeanFrontier/"):-len(".lean")].replace("/", ".")
        blobs[name] = meta.split()[2]
    if not blobs:
        return {}
    # Binary: `cat-file --batch` reports sizes in bytes, and Lean sources are
    # full of multibyte notation, so decoding first would misplace every offset.
    request = "".join(f"{sha}\n" for sha in blobs.values()).encode("ascii")
    batch = subprocess.run(["git", "-C", str(root), "cat-file", "--batch"], input=request, capture_output=True, check=True).stdout
    sources: dict[str, str] = {}
    offset = 0
    for name in blobs:
        newline = batch.index(b"\n", offset)
        size = int(batch[offset:newline].split()[2])
        start = newline + 1
        sources[name] = batch[start:start + size].decode("utf-8", errors="replace")
        offset = start + size + 1
    return sources


def edges_of(sources: dict[str, str]) -> list[tuple[str, str]]:
    known = set(sources)
    return [(name, target) for name, source in sources.items() for target in IMPORT_RE.findall(source) if target in known]


def depth_of(sources: dict[str, str], edges: list[tuple[str, str]]) -> int:
    outgoing: dict[str, list[str]] = {name: [] for name in sources}
    for source, target in edges:
        outgoing[source].append(target)
    memo: dict[str, int] = {}

    def depth(name: str, seen: frozenset[str] = frozenset()) -> int:
        if name in memo:
            return memo[name]
        if name in seen:  # a cycle cannot arise from Lean imports, but never hang on one
            return 0
        memo[name] = 1 + max((depth(target, seen | {name}) for target in outgoing[name]), default=0)
        return memo[name]

    return max((depth(name) for name in sources), default=0)


def rows(root: Path) -> list[tuple[str, ...]]:
    first_seen: dict[str, date] = {}
    result: list[tuple[str, ...]] = []
    for commit, day, submission in submission_commits(root):
        sources = modules_at(commit, root)
        if not sources:
            continue
        accepted = date.fromisoformat(day)
        edges = edges_of(sources)
        for name in sources:
            first_seen.setdefault(name, accepted)
        incoming: dict[str, int] = {}
        connected = set()
        for source, target in edges:
            incoming[target] = incoming.get(target, 0) + 1
            connected.add(source)
        # Did this submission's own new modules import anything accepted recently?
        fresh = [name for name, seen in first_seen.items() if seen == accepted]
        recent = any(
            (accepted - first_seen[target]).days <= RECENT_DAYS
            for source, target in edges
            if source in fresh and target in first_seen
        )
        result.append((
            day,
            submission,
            str(len(sources)),
            str(len(edges)),
            f"{len(edges) / len(sources):.3f}",
            f"{len(connected) / len(sources):.3f}",
            str(max(incoming.values(), default=0)),
            str(depth_of(sources, edges)),
            "true" if recent else "false",
            "true" if accepted >= ADD_ONLY_SINCE else "false",
        ))
    return result


def render(root: Path) -> str:
    return HEADER + "".join(",".join(row) + "\n" for row in rows(root))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = args.root / DESTINATION
    expected = render(args.root)
    existing = destination.read_text(encoding="utf-8") if destination.exists() else ""
    if expected == existing:
        return 0
    if args.check:
        print(f"{destination} is stale; run tools/generate_accumulation_series.py")
        return 1
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
